before_script:
  # update the CI runner package that determines build orders and such
  - git submodule init
  - git submodule update
  - echo "Updating CI tool"
  - pushd ~/code/conda-gitlab-ci
  - python setup.py develop
  - popd
  #- conda install -qy -c msarahan conda-gitlab-ci
  #- conda update -qy -c msarahan conda-gitlab-ci
  - cgci --version

# the first pass examines the difference in the repo from the given two commits
determine_builds:
  script:
    - cgci .

# this CI script is called once by each worker (by label) for each recipe.  The variables
#    that it is called with changes, and those calls are done with the
#    determine_builds target.
build_recipe:
  only:
    - triggers
  script:
    # Replace this with a script.  gitlab does not recognize multliline input.
    # https://gitlab.com/gitlab-org/gitlab-ci-multi-runner/issues/166
    - if [ -n "$BUILD_RECIPE" ]; then conda build --token $ANACONDA_TOKEN $TEST_MODE $BUILD_RECIPE -c conda_gitlab; fi
        # copy built package to desired output repo
