resource_types:
# used to download arbitrary user configuration (credentials, platforms, and versions.yml)
- name: s3-simple
  type: docker-image
  source:
    repository: 18fgsa/s3-resource-simple
# used to check for PRs and update status at Github
- name: pull-request
  type: docker-image
  source:
    repository: jtarchie/pr

resources:
# - name: recipe-repo-source
#   type: pull-request
#   source:
#     repo: {{recipe-repo}}
#     access_token: {{recipe-repo-access-token}}

- name: recipe-repo-source
  type: git
  source:
    url: {{recipe-repo}}


- name: version
  type: semver
  source:
    bucket: {{aws-bucket}}
    key: {{version-file}}
    secret_access_key: {{aws-secret-key}}
    access_key_id: {{aws-key-id}}
    region_name: {{aws-region-name}}
    initial_version: 1.0.0

- name: s3-archive
  type: s3
  source:
    bucket: {{aws-bucket}}
    access_key_id: {{aws-key-id}}
    secret_access_key: {{aws-secret-key}}
    region_name: {{aws-region-name}}
    # this is the output folder on aws, not the local location.
    regexp: {{tarball-regex}}

# this is a folder of all of our initial configuration.  No pushing here.
- name: s3-config-base
  type: s3-simple
  trigger: true
  source:
    bucket: {{aws-bucket}}
    secret_access_key: {{aws-secret-key}}
    access_key_id: {{aws-key-id}}
    region_name: {{aws-region-name}}
    options: [--exclude '*', --include {{config-folder-star}}]

jobs:
- name: collect-tasks
  public: True
  plan:
  # pull down any PR submitted
  - get: recipe-repo-source
    trigger: true
    submodules: all
  # update status for that PR
  # - put: recipe-repo-source
  #   params:
  #     path: recipe-repo-source
  #     status: pending
  - get: s3-config-base
  - get: version
    params:
      bump: patch

  - task: install-run-c3i
    config:
      # seems redundant, but you need this in order to have the repo source code folder show up
      inputs:
        - name: recipe-repo-source
        - name: s3-config-base
        - name: version
      outputs:
        - name: output
      image_resource:
        type: docker-image
        source:
          repository: msarahan/conda-concourse-ci
      platform: linux
      run:
        path: c3i
        args: [examine, recipe-repo-source, {{base-name}}, --matrix-base-dir, s3-config-base/{{config-folder}}]
  - put: version
    params:
      file: version/version
  # this should trigger the execute pipeline
  - put: s3-archive
    params:
      # this is the relative location on local disk
      file: {{tarball-glob}}
  - put: recipe-repo-source
    params:
      path: recipe-repo-source
      status: pending
  - task: set-execute-pipeline
    config:
      inputs:
        - name: s3-config-base
        - name: output
        - name: recipe-repo-source
        - name: version
      image_resource:
        type: docker-image
        source:
          repository: msarahan/conda-concourse-ci
      platform: linux
      run:
        path: c3i
        # TODO: need to determine what private/public status is, and set child accordingly
        args:
          - submit
          - {{base-name}}
          - --pipeline-file
          - output/plan.yml
          - --pipeline-name
          # these template variables are filled in by the c3i program, NOT concourse.
          - "{base_name}-execute-{git_identifier}"
          - --src-dir
          - recipe-repo-source
