label: centos5-64
platform: linux
arch: 64
# this section is optional.  Only linux docker containers are supported this way right now.
connector:
  image_resource:
    type: docker-image
    source:
      repository: msarahan/conda-concourse-ci
      tag: latest
